export const KEY_LINE_RESOURCE = 'line';
export const GET_INITIAL_DATA_LINES = 'ReturnLines/GET_INITIAL_DATA_LINES';

export const CHANGE_ATTRIBUTE_TABLE = 'ReturnLines/CHANGE_ATTRIBUTE_TABLE';
export const SET_ATTRIBUTE_TABLE = 'ReturnLines/SET_ATTRIBUTE_TABLE';
